### PR TITLE
Allow the "@" character when parse jira usernames

### LINKED ISSUE #924: Mention notification doesn't work if username contains "@"
Jira Version: 8.17.0
Mattemost Version: 7.8.1

Hi! 

In our company, **JIRA** users have a username that is equal  to their email. We've noticed that mention notifications in direct messages aren't working. 

I analyzed the [parseJIRAUsernamesFromText](https://github.com/mattermost/mattermost-plugin-jira/blob/a7f0e417ba67ba5a0113815cad2d6f655aceffc3/server/utils.go#L111)  function, which used to get JIRA usernames from the text inside the `appendCommentNotifications` function and noticed that the [regular expression](https://github.com/mattermost/mattermost-plugin-jira/blob/a7f0e417ba67ba5a0113815cad2d6f655aceffc3/server/utils.go#L115) does not contain the "@" character. I tested the regular expression separately to confirm the issue (see screenshot below).  

зображення

I think we need add '@' to the regex expression to solve it problem. 

зображення

### PR DESCRIPTION
**Pull request by korkoshko**
Fixes #924.

I tested these changes using my personal build of the plugin.

P.S I can also add tests to it if needed.

### CODE REVIEW

**Comment by mickmister** [comment]
@korkoshko This fix looks good to me :+1: 

> P.S I can also add tests to it if needed.

This would very much be welcomed :+1: It looks like a good file for this would be `server/webhook_parser_misc_test.go`

**Comment by korkoshko** [comment]
Thanks [mickmister](https://github.com/mickmister)! 

> This would very much be welcomed. It looks like a good file for this would be `server/webhook_parser_misc_test.go`. Please let me know your thoughts on adding a test there.

I think it's better add unit tests for the `parseJIRAUsernamesFromText` function and put them in `server/utils_test.go`. This makes it easy to test many variations of JIRA nicknames.

**Comment by mickmister** [comment]
@korkoshko Makes sense to me :+1: Perfect function for a unit test

**Comment by korkoshko** [comment]
@mickmister test added!

**Review by trilopin — APPROVED** [review]
LGTM

Thank you @korkoshko for your help 💯

**Comment by mickmister** [comment]
@DHaussermann I'm thinking we can defer testing on this. The PR adds a test for a function that previously didn't have tests. There are several cases covered in the tests, including corner cases that are related to this PR's fix. Please take a look at the files changes and let me know your thoughts

**Pull request merged**
