### PR TITLE
[GH-558] Fix issue: /jira assign should accept @username

### LINKED ISSUE #558: `/jira assign` should accept `@username`
Currently, the first parameter is interpreted solely as a search string for a Jira user search. We should support accepting an `@username`. If the user is connected to the instance, we can use the AccountID; if not - can perform a Jira search on the Mattermost display name.

### PR DESCRIPTION
**Pull request by raghavaggarwal2308**
### Summary

Most of the changes in this PR are from PR #863. We just added the support to search for Jira users in case the @ symbol is not present as the prefix in the username [(i.e. the approach which was being used earlier)](https://github.com/mattermost/mattermost-plugin-jira/pull/863#issuecomment-1447565847). Also, we fixed a small issue, in case the mentioned user account was not connected to Jira, the Jira issue was getting unassigned.

## Demo video
[Demo video for updated flow](https://user-images.githubusercontent.com/55234496/236236419-54388f45-4f90-45b2-bd84-1ab8faa844b6.webm)

### Ticket
Fixes #558 ( /jira assign should accept @username)

### CODE REVIEW

**Comment by raghavaggarwal2308** [comment]
@mickmister Fixed the review comments mentioned by you

**Review by srkgupta — APPROVED** [review]
Thanks @raghavaggarwal2308. LGTM 🎉

**Review by mickmister — APPROVED** [review]

**Comment by raghavaggarwal2308** [comment]
@DHaussermann Gentle reminder for review

**Comment by raghavaggarwal2308** [comment]
@DHaussermann Gentle reminder for review

**Comment by raghavaggarwal2308** [comment]
@DHaussermann Gentle reminder for review

**Comment by raghavaggarwal2308** [comment]
@DHaussermann Gentle reminder for review

**Comment by raghavaggarwal2308** [comment]
@DHaussermann Gentle reminder for review

**Comment by hanzei** [comment]
@AayushChaudhary0001 Would you be open to reviewing this PR?

**Review by AayushChaudhary0001 — APPROVED** [review]

**Pull request merged**
