### PR TITLE
[Fix: #719]: Correct error messages for multiple Jira instances

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary

This PR aims to solve #719 

#### Ticket Link

#719

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM :+1: Thanks @haardikdharma10!

**Review by jfrerich — APPROVED** [review]
Looks great :) Thanks, @haardikdharma10!

**Comment by haardikdharma10** [comment]
Hi @DHaussermann, can you review this and let us know if this PR is ready to merge?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Confirmed the new text shows as expected
- Text now more explicitly states `Enterprise E20 License`
- Brief regression testing with connect / disconnect No issues found

LGTM!

Thanks @haardikdharma10 for this enhancement! Sorry for the delay with testing this. This is ready to merge.

**Pull request merged**
