### PR TITLE
Bump version to 4.1.0

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

- https://github.com/mattermost/mattermost-plugin-jira/pull/995
- https://github.com/mattermost/mattermost-plugin-jira/pull/1002
- https://github.com/mattermost/mattermost-plugin-jira/pull/986
- https://github.com/mattermost/mattermost-plugin-jira/pull/962
- https://github.com/mattermost/mattermost-plugin-jira/pull/887
- https://github.com/mattermost/mattermost-plugin-jira/pull/983
- https://github.com/mattermost/mattermost-plugin-jira/pull/938
- https://github.com/mattermost/mattermost-plugin-jira/pull/1008
- https://github.com/mattermost/mattermost-plugin-jira/pull/1004
- https://github.com/mattermost/mattermost-plugin-jira/pull/988
- https://github.com/mattermost/mattermost-plugin-jira/pull/1017
- https://github.com/mattermost/mattermost-plugin-jira/pull/1013

### CODE REVIEW

**Review by raghavaggarwal2308 — APPROVED** [review]

**Review by avas27JTG — APPROVED** [review]

**Review by arush-vashishtha — APPROVED** [review]
Tested and approved
All the PR's included are working fine and the overall functionality works well, LGTM.

Testing found no blockers; nonetheless, few lower priority enhancements were discovered, for which below issues are created and planned to be picked in the next release.
https://github.com/mattermost/mattermost-plugin-jira/issues/1010
https://github.com/mattermost/mattermost-plugin-jira/issues/1011

**Pull request merged**
