### PR TITLE
[MM-18533] Add channel header button to open subscribe modal

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR adds the Jira subscribe modal button in the channel header. This code was originally removed [here](https://github.com/mattermost/mattermost-plugin-jira/pull/270).

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18533

#### Screenshots

image
image

### CODE REVIEW

**Comment by DHaussermann** [comment]
- Tested on cloud and server
- Icon only visible while user is connected to Jira
- Icon respects previous permissions for open subscriptions modal

Couple follow-up points on this...
1. @mickmister  your screen above show the plug icon when there are multiple plugins but I see "..."  Do we know which is the expected behavior?
2. @aaronrothschild One minor drawback to having the subscribe option more visible is that all connected users will see it regardless of if the have access to open the modal. I don't see much we can do about this given we can't hide this icon from some users and the permissions can be different from one channel to another. We may want a future story for a different UX for this.
3. There is an issue where the left edge of icons is cut off when there are multiple but, it's not specific to jira and we have an existing ticket for it. 
PluginIcons

**Comment by aaronrothschild** [comment]
@DHaussermann Agreed - there may be more exposure to this feature and some users will encounter a permissions error, however that is limited to people who have already connected their Jira account to MM.  The last time we made this change, we definitely got initial feedback that it was very prominent and I wonder how many users will click it out of curiosity and be greeted with the permissions error screen...Perhaps we can change this text to explain what the user could do do with the Jira plugin a bit more?  
image

For example:
"Sorry, you don't have permission to edit the subscriptions for this channel.  Configuring a Jira subscription notification will create notifications in this channel when certain events happen in Jira, such as an issue being updated or created with a specific label.  Speak to your Mattermost administrator to request access to this functionality."

@mickmister I'll throw it out there, knowing that this is Toolkit team territory (cc @lieut-data ) - How much Mana would be involved in creating a plugin hook to the Channel Menu so that we could place a "Jira Subscription" item in there? 
image

**Comment by mickmister** [comment]
@aaronrothschild

> @mickmister I'll throw it out there, knowing that this is Toolkit team territory (cc @lieut-data ) - How much Mana would be involved in creating a plugin hook to the Channel Menu so that we could place a "Jira Subscription" item in there?

I think it would be a 8-12 mana task to add a new button in that menu. I'm not sure what all goes into that.

As for the wording of the message when there is a permission issue, I like the idea of offloading explanations of things to the docs. It is good practice as our docs become more and more informative. I'm not sure if it applies here though.

**Comment by aaronrothschild** [comment]
> As for the wording of the message when there is a permission issue, I like the idea of offloading explanations of things to the docs. It is good practice as our docs become more and more informative. I'm not sure if it applies here though.

My thought is that the text is explaining what the function they don't have access to, is used for.  That explanation shouldn't really change over time (but the detailed documentation might) and is friendlier for users (they can shrug and say "I don't need that anyhow") rather than a slightly mysterious message and a desire to google/look up our docs to see what "Jira subscriptions" are. 3/5 Should I create another issue to change the text?

**Comment by mickmister** [comment]
> Should I create another issue to change the text?

Sounds good to me :+1:

**Comment by aaronrothschild** [comment]
Done: https://mattermost.atlassian.net/browse/MM-19793

**Comment by lieut-data** [comment]
> I think it would be a 8-12 mana task to add a new button in that menu. I'm not sure what all goes into that.

4 mana if we just expose the ability to include the menu option. But I'm hearing the need to gate options according to permissions automatically. Maybe doesn't need to be coupled to the feature, since it's more "buried" either way. @aaronrothschild, should we sync on this at KIT-INT?

**Comment by mickmister** [comment]
@aaronrothschild Should this PR be closed because we are going to go a different route for the modal button?

**Comment by aaronrothschild** [comment]
> @aaronrothschild Should this PR be closed because we are going to go a different route for the modal button?

@mickmister Hold off on closing it.  I've made a ticket to allow Plugins access to the Channel Actions Menu:  https://mattermost.atlassian.net/browse/MM-19902

Adding "Jira Subscriptions" to the menu:  https://mattermost.atlassian.net/browse/MM-19905

> 4 mana if we just expose the ability to include the menu option.

@lieut-data can we chat before the next KIT-INT meeting?

**Pull request closed without merging**
