### PR TITLE
[ MM-15015] Add jira Icons to create and attach post menu items

### PR DESCRIPTION
**Pull request by jfrerich**
**Summary**
Jira Icons to the `create jira issue` and `attach jira issue` menu items in the post menu pulldown.

image

**Ticket Link**
Please view the following Jira ticket and the link to invisionapp spec.
https://mattermost.atlassian.net/browse/MM-15015

https://projects.invisionapp.com/share/QZQIQ9YKH9T#/screens/352192993

### CODE REVIEW

**Comment by jasonblais** [comment]
Does the icon appear a bit blurry on the attached screenshot above?

**Comment by jfrerich** [comment]
@jasonblais yes, let me double check this is the .png file I got from Asaad

**Comment by jfrerich** [comment]
@asaadmahmood the icon from assets in invisionapp seems to be a bit pixelated.  Do we have a clearer version?  Thanks

**Comment by asaadmahmood** [comment]
@jfrerich I have used an icon here, have a look.
https://github.com/mattermost/mattermost-plugin-jira/pull/61

**Comment by jfrerich** [comment]
After adding the line separator and SVG icons.

image

**Comment by jfrerich** [comment]
Thanks @asaadmahmood

**Pull request merged**
