### PR TITLE
[MM-1028]: Fixed the issue of title being truncated without ellipses in tooltip modal

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
### Summary
- Fixed the issue of the title being truncated without ellipses in the tooltip modal
 Added hover text for the tooltip title

### Ticket Link
  Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1028
  Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1077

#### Title
Screenshot from 2024-09-20 11-15-21
#### Old
Screenshot from 2024-09-20 11-17-30
#### New
Screenshot from 2024-10-25 14-29-35

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by AayushChaudhary0001** [comment]
@Kshitij-Katiyar While testing this PR, I found a minor issue related to extra spaces in the title in Jira issue.
If we try to add extra spaces in between the words of the title of a Jira issue, it is shown with proper spacing on Jira. But if we hover over the link of the same ticket on MM, then the text gets truncated as if the text length is too long. I am attaching the screenshot below, please take reference from those.

**On adding extra spaces:-**
image


**On saving the title on Jira:-**

image




**On hovering on MM:-**
image

**Comment by Kshitij-Katiyar** [comment]
> @Kshitij-Katiyar While testing this PR, I found a minor issue related to extra spaces in the title in Jira issue. If we try to add extra spaces in between the words of the title of a Jira issue, it is shown with proper spacing on Jira. But if we hover over the link of the same ticket on MM, then the text gets truncated as if the text length is too long. I am attaching the screenshot below, please take reference from those.
> 
> **On adding extra spaces:-** image
> 
> **On saving the title on Jira:-**
> 
> image
> 
> **On hovering on MM:-** image

Hey @AayushChaudhary0001, I created a similar ticket on JIra and checked the data sent by Jira to the MM server, it looks like the handling of the extra spaces between the words is on the client side of Jira and the data is stored on the server with the extra spaces only because we are receiving the ticket summary with the extra spaces on the MM server.
I am afraid there is no proper way to fix this issue

**Comment by raghavaggarwal2308** [comment]
@Kshitij-Katiyar @AayushChaudhary0001 I think we should match the functionality of Jira here. If Jira is removing the extra spaces we should also do the same.

**Comment by Kshitij-Katiyar** [comment]
> @Kshitij-Katiyar @AayushChaudhary0001 I think we should match the functionality of Jira here. If Jira is removing the extra spaces we should also do the same.

@AayushChaudhary0001 @raghavaggarwal2308 I have implemented the same. Please re test it @AayushChaudhary0001

**Review by raghavaggarwal2308 — APPROVED** [review]

**Review by AayushChaudhary0001 — APPROVED** [review]
The PR has been tested for the above fix, LGTM. Approved.

**Pull request merged**
