### PR TITLE
[MM-19705] Add back button to edit subscription modal

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR adds a back button to the edit subscription part of the subscriptions modal, so you can return to the select subscription part without clicking cancel.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19705

#### Screenshots

image

### CODE REVIEW

**Comment by mickmister** [comment]
@asaadmahmood Should the close button also have the accessibility change?

**Comment by asaadmahmood** [comment]
@mickmister Yes, it should be a button.

**Comment by mickmister** [comment]
@DHaussermann The back button does not go behind the other elements now.

**Comment by DHaussermann** [comment]
This was successfully implemented.  

@asaadmahmood can you please confirm the buttons should have the color when you mouse-over the button.

 Hover

**Comment by asaadmahmood** [comment]
@DHaussermann Should have the same hover styling as the close button in the Invite People modal on daily.
Screenshot 2019-11-01 at 8 22 31 PM

**Comment by DHaussermann** [comment]
Thanks @asaadmahmood . Yes it matches the close button.

**Comment by asaadmahmood** [comment]
@DHaussermann That screenshot does not look like it matches it, the background should be lighter.
It should be: `var(--button-bg-10)`.

@mickmister See comment.

**Comment by DHaussermann** [comment]
To clarify, I meant that the close button is also showing the darker color based on selected theme.

**Comment by asaadmahmood** [comment]
Cool. Yeah, but it should be lighter.

**Comment by mickmister** [comment]
@asaadmahmood @DHaussermann fixes applied for the button color issues

**Pull request merged**
