### PR TITLE
[GH-857]: Fixed Jira bot DMs you when you mention yourself in a comment

### LINKED ISSUE #857: Jira bot DMs you if you mention yourself in a comment on a Jira issue

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
### Summary
- Fixed the issue of Jira bot DMs you when you mention yourself in a comment

### Issue Link
Fixes #857 

### What to test
- Jira bot sending you DM when you mention yourself in a comment

### How to test
- Install the plugin
- Configure & setup the plugin
- Create & connect the webhook
- mention yourself in a comment on a Jira issue

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@Kshitij-Katiyar Does this work for Jira Cloud and Server? I'm thinking maybe this was just broken for Jira Cloud?

**Comment by mickmister** [comment]
@Kshitij-Katiyar Does this need QA review or is this ready for merge?

**Comment by raghavaggarwal2308** [comment]
@mickmister I think it would be better to get it tested by a QA before merging.

**Review by AayushChaudhary0001 — APPROVED** [review]
Tested this PR, working fine for all the DMs sent by Jira bot when the user is getting mentioned in a comment. LGTM, Approved.

**Comment by raghavaggarwal2308** [comment]
@AayushChaudhary0001 The issue should be fixed now. Please verify.

**Review by wiggin77 — APPROVED** [review]

**Pull request merged**
