### PR TITLE
[issue 773] Jira's autolink should support issue links that contain a comment link in the URL

### LINKED ISSUE #773: Jira's autolink should support issue links that contain a comment link in the URL
Currently the autolink config used by this plugin converts issue links to shorthand links, but it does not work when the originally posted URL has a comment link at the end of the posted URL.

Here's an example provided by an admin that works with comments:

```json
{
    "DisableNonWordPrefix": false,
    "DisableNonWordSuffix": false,
    "Disabled": false,
    "Name": "jirajumptocomment",
    "Pattern": "https://something.atlassian.net/browse/(?P\u003cIssueKey\u003e[A-Za-z]+-[0-9]+)[?]focusedCommentId[^\\s]+",
    "Scope": null,
    "Template": "[${IssueKey} Link to comment]($0)",
    "WordMatch": false
}
```

Discussed in https://community-daily.mattermost.com/private-core/pl/fkeoiwqbmbyrxrqnap877jykbo

### PR DESCRIPTION
**Pull request by sibasankarnayak**
added autolink for link that contain a comment link

ticket here

Fixes #773

### CODE REVIEW

**Review by aspleenic — APPROVED** [review]

**Comment by sibasankarnayak** [comment]
@mickmister as discussed over call , confirmed that autolink feature works in master and kept the shorthand and added the project independent regex for ticket url and comment url

**Comment by mickmister** [comment]
@dipak-demansol When you review this, please test the plugin upgrade path. Meaning:

- Install the previous version of the Jira plugin
- Install Jira instance with several projects
- Note the autolink entries that were created
- Install this version of the plugin
- Note the autolink entries. Please post the result here.
- Test behavior of posting ticket links with the form:
    - `https://mattermost.atlassian.net/browse/MM-12345?focusedCommentId=10210`
    - `https://mattermost.atlassian.net/browse/MM-12345`
    - `MM-12345` (should only work with Jira Cloud)

Please test with Jira Cloud and Jira Server

**Comment by dipak-demansol** [comment]
@sibasankarnayak @mickmister i can still see the same output before and after installing the PR build.
image

steps 1) installed the market jira build.
         2) Connected with the jira instance. (autolink was already Configured) 
         3) paste the link of the comment from that same instance, pls see the attachment image.
         4) installed the PR build and paste again the same link and got the same output, pls see the attachment image.

**Comment by sibasankarnayak** [comment]
> talled the market jira build.

I see you install the  market jira build that doesn't contain the solution , try installing this PR and then do test with required step.

**Review by dipak-demansol — CHANGES_REQUESTED** [review]
please check this comment @sibasankarnayak https://github.com/mattermost/mattermost-plugin-jira/pull/839#issuecomment-1125096539

**Comment by dipak-demansol** [comment]
@DHaussermann i Used the same build and it worked for me this time, i just removed the jira instance and connected again but you and me we also did the same thing and it was not worked for us so need to investigate that what was the exact reason because of that the same build previously  not worked for us.  **its working still without knowing the cause of the issue i can't pass this.**

attacking the screenshot as its now worked for me, 
image

**Pull request closed without merging**
