### PR TITLE
[GH-676] Handle missing comment events for "Issue Updated: Any"

### LINKED ISSUE #676: `Issue Updated: Any` subscription setting should include catch all comment events
For Jira Cloud and Server `Issue Updated Any` is only capturing Comment Updated events. `Comment Created` and `Comment Deleted` events do not appear when you are subscribed to Any

**Note** An issue mentioned in this task specific to Cloud has been removed. This was an error caused by webhook misconfiguration

### PR DESCRIPTION
**Pull request by promulo**
#### Summary
This PR fixes an issue with the channel subscription of type `Issue Updated: Any`. Currently, channels with that type of subscription are not receiving `event_created_comment` and `event_deleted_comment`. This is changed by including the handling of those events when deciding if the current channel subscriptions are interested the current webhook. Some unit tests are also included.

#### Ticket Link
Fixes #676 

#### Screenshots
Tested on macOS with Jira Cloud.
image

Thanks for reviewing!

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
Thanks @promulo!  I think this makes sense, but am wondering if checking "comment" as a prefix will catch event types besides, command updated and comment deleted?

**Comment by promulo** [comment]
Hi @jfrerich , thanks for reviewing. From what I could verify, the only events that have the `comment` suffix are the three we're interested on: `event_created_comment`, `event_updated_comment` and `event_deleted_comment`. They are defined here: https://github.com/mattermost/mattermost-plugin-jira/blob/49cf6c30d65284a9bfe9d534c1a3a92ba83a672c/server/event_types.go#L3

**Review by mickmister — APPROVED** [review]
Looks great! Thanks @promulo!

**Comment by mickmister** [comment]
@aaronrothschild @DHaussermann Note that this is a UX change. `Issue Updated: Any` now covers comment events (which is definitely desirable). The change is entirely backend, and all existing subscriptions set up to use `Issue Updated: Any` will have this effect.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- `Issue Updated: Any` now includes Issue creation and issue deletion
- No changes to comment update
- No issues found

LGTM!

Thanks @promulo  for the PR!

**Pull request merged**
