### PR TITLE
[MM-19815] When saving a subscription, remove fields that are not in the issue metadata

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

If a field is configured in a subscription, and is then deleted or removed from an issue type in Jira, the filter will cause no webhook events to match the subscription. This PR makes it so the broken field can be removed from the subscription.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19815

#### Additional Info

I also got rid of some superfluous snapshot tests that were causing a lot of bloat in the snapshots.

### CODE REVIEW

**Comment by mickmister** [comment]
image

**Comment by aaronrothschild** [comment]
@mickmister Ya, the user won't be able to "undelete" the field or anything, so I think just the error is OK.  I think the bigger question is: After I delete a field in Jira - do certain subscriptions stop working silently?

**Comment by mickmister** [comment]
> After I delete a field in Jira - do certain subscriptions stop working silently?

@aaronrothschild Yes, unfortunately. The only way to "fix" the subscription is for the user to go to the form here and submit the form. It will remove the nonexistent fields.

I'm not sure if we want to go the route of continuous housekeeping and sync between the systems. It may be beneficial to have functionality to perform sync, then the admin can manually do so when they need to? cc @levb

**Comment by aaronrothschild** [comment]
> > After I delete a field in Jira - do certain subscriptions stop working silently?
> 
> @aaronrothschild Yes, unfortunately. The only way to "fix" the subscription is for the user to go to the form here and submit the form. It will remove the nonexistent fields.
> 
> I'm not sure if we want to go the route of continuous housekeeping and sync between the systems. It may be beneficial to have functionality to perform sync, then the admin can manually do so when they need to? cc @levb

At the very least, do we log this as an error somewhere? (ie: I have a subscription that become non-operational because a field is missing, does the notification fail without an error logged anywhere?)

**Comment by levb** [comment]
I think detecting and displaying meaningful errors may be complicated. I would instead opt for collecting and displaying the individual subscription's statistics, including the last time we got a messages, and the number of messages received in the last 30 days? This way the user can see what subs have gone stale and investigate from there.

**Comment by mickmister** [comment]
> I would instead opt for collecting and displaying the individual subscription's statistics, including the last time we got a messages, and the number of messages received in the last 30 days?

@levb Sounds good to me, should we ticket this?

FWIW we do have an opportunity to assert that a field is not present in the webhook call. Currently, this is handled the same way as the value being blank.

**Comment by aaronrothschild** [comment]
> FWIW we do have an opportunity to assert that a field is not present in the webhook call. Currently, this is handled the same way as the value being blank.

@mickmister can you expand on this?

**Comment by levb** [comment]
I think that perhaps what we ought to do is that when one attempts to edit a subscription, and it contains a field that is no longer available, we display a warning and recommend (re-)saving the subscription. A separate ticket/PR? @mickmister @aaronrothschild?

**Comment by aaronrothschild** [comment]
> I think that perhaps what we ought to do is that when one attempts to edit a subscription, and it contains a field that is no longer available, we display a warning and recommend (re-)saving the subscription. A separate ticket/PR? @mickmister @aaronrothschild?

@levb Yes, I think that's exactly what this PR does :) The other solutions don't seem to make much technical sense, so let's leave this as the approach.  

It may become a problem over time where Admins don't know that channels are no longer receiving notifications because a field was deleted and is silently failing, we can perhaps address in future with stats logging of how many messages get sent to each channel in the past X months, so the admin can notice Subscriptions with "0" activity (you'd suggested this previously in this thread).

**Comment by mickmister** [comment]
@aaronrothschild Friendly ping to review this as it stands

**Pull request merged**
