### PR TITLE
Add batch method to call to mock.AnythingOfTypeArgument

### LINKED ISSUE #590: Refactor test code to use avoid superfluous calls to `mock.AnythingOfTypeArgument("string")`
Our test code is riddled with several sequential calls to `mock.AnythingOfTypeArgument("string")`. We can instead create a helper function like `mockBatch("string", numCalls)` to do this in one line. Here's an example:

https://github.com/mattermost/mattermost-plugin-jira/blob/dd988f94ebcf834806aeabefc470b410977dc187/server/issue_test.go#L212-L225

### PR DESCRIPTION
**Pull request by vladimirdotk**
#### Summary

- Add function for batch calls to mock.AnythingOfTypeArgument
- Substitute calls to mock.AnythingOfTypeArgument to a new function

#### Ticket Link

Closes #590

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
Great work @vladimirdotk! Love seeing all of the deletions!!

**Review by jfrerich — APPROVED** [review]
Thanks for the PR @vladimirdotk!  Very much appreciated!

**Comment by jfrerich** [comment]
@mickmister, CI is passing and no functional code was modified.  What do you think about bypassing the QA for this one?

**Comment by mickmister** [comment]
@jfrerich Sounds good to me :+1:

Thanks @vladimirdotk!!

**Pull request merged**
