### PR TITLE
Post command response in RHS if triggered from there

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Same bug as for GH

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/683

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei I believe this is working as expected. For the most part all responses are posted in the RHS when the command is sent from there. 

I notice that this is not the case for Jira `view` which creates a post with a visual representation of the issue. I'm assuming this is the expected behavior. I don't know what such a post would look like in the RHS where there is limited horizontal space for the elements. 

Can you confirm this change does not apply yo Jira `view`
Screen Shot 2020-10-09 at 9 41 07 AM

**Comment by hanzei** [comment]
@DHaussermann Actually, it should post in the RHS. I've fixed that. PTAL

**Comment by hanzei** [comment]
@DHaussermann I'm fairly confident that these two issues aren't related to this PR. Please open a new ticket for them.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested all slash commands in RHS 
- Reply is also show in the RHS as expected
- Issue found with `/jira view has now been addressed`
- Created https://github.com/mattermost/mattermost-plugin-jira/issues/698 to investigate and resolve JS errors found 

LGTM!

**Pull request merged**
