### PR TITLE
Remove workflow functionality and dependency

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This repo imports the autolink plugin and workflow plugin client as dependencies, which has caused some issues with importing certain versions of mattermost-server. Part of the problem is some of the paths have changed to the packages in mattermost-server.

Removing the workflow client dependency resolved a lot of the issues. I figure the workflow functionality should be removed from the plugin anyway because the workflow plugin is no longer in development.

### CODE REVIEW

**Comment by mickmister** [comment]
@hanzei I've run `go mod tidy` but I'm running into CI errors saying that it should be run again

**Comment by hanzei** [comment]
@mickmister Did you used go1.16 to run `go mod tidy`?

**Comment by hanzei** [comment]
@mickmister Heads up that I run `go mod tidy` to fix the CI issue.

**Review by hanzei — APPROVED** [review]

**Review by crspeller — APPROVED** [review]

**Comment by mickmister** [comment]
> @mickmister Did you used go1.16 to run `go mod tidy`?

@hanzei I don't think so. I'll make sure I do from now on though, thank you

**Pull request merged**
