### PR TITLE
Merge master into channel subscriptions

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR updates the `feature/channel-subscriptions` branch to be in line with the `master` branch.

### CODE REVIEW

**Comment by cpoile** [comment]
@mickmister Is this something we need to carefully review?

**Comment by levb** [comment]
@cpoile: This is a back-merge, in preparation to make the (out-of-sync) feature branch mergeable to master. So careful - yes, but it will then be diff-ed and reviewed when merging back to master.  @mickmister - right?

**Comment by mickmister** [comment]
@levb yes that's correct. This PR is fairly small, the bulk of it coming from tests and test data. The PR to merge channel-subscriptions into master will be a 
bigger effort to review.

**Comment by levb** [comment]
@DHaussermann does this really need a QA review? Seems like we should rely on the QA review of the feature branch itself, once the diffs are established.

**Comment by DHaussermann** [comment]
@levb I was thinking the same. Seems more efficient to test on the branch post merge. I can create follow-up tasks to be addresses as separate PRs if needed.

Not sure this is the appropriate place to ask but... Since we're pulling the maintenance into the feature branch, I wonder when will be merging the subscribe feature into master?

**Pull request merged**
