### PR TITLE
[Fix: #657] : Drop Fetching subscriptions ephemeral post

### PR DESCRIPTION
**Pull request by haardikdharma10**
#### Summary
Aims to solve https://github.com/mattermost/mattermost-plugin-jira/issues/657

#### Ticket Link

Fixes: https://github.com/mattermost/mattermost-plugin-jira/issues/657

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]
LGTM!

**Review by jfrerich — APPROVED** [review]

**Comment by michelengelen** [comment]
LGTM! 
Thanks for the contribution! 👍🏻

**Review by michelengelen — APPROVED** [review]

**Review by levb — APPROVED** [review]

**Comment by michelengelen** [comment]
kind reminder for @DHaussermann

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- User now only see's the 2nd ephemeral post regarding not having permission when access is denied
- The 1st post regarding fetching no longer appears
- Regression tested no changes when modal opens

LGTM!
Thanks @haardikdharma10  for this enhancement. Much appreciated!

**Pull request merged**
