### PR TITLE
MM-19674: use respondXXX in http handlers

### PR DESCRIPTION
**Pull request by levb**
#### Summary
There was some funky error handling in http functions, streamlined it, should now consistently use `respondErr` when returning errors in http handlers.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-19674

### CODE REVIEW

**Comment by levb** [comment]
@DHaussermann there is not too much you can test here other than for general regressions. Most of the changes affect the error paths, but technically most of the http endpoints are affected.

**Comment by DHaussermann** [comment]
Regression tested some server side error cases:

**Comment by DHaussermann** [comment]
Regression tested some server-side error cases
- Summary length 
- Description length 
- User permission revoked 
- Jira instance unavailable 
- Project has become un-available 

@levb In some cases when validating the length, there are extra characters appearing in the validation text. I'm not entirely sure it was introduced by this PR. Should this be a separate issue?
DescriptionValidation
SummaryValidation

**Comment by levb** [comment]
@DHaussermann fixed

**Comment by hanzei** [comment]
@levb @jfrerich Heads up that this PR has broken `master`: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-jira/1723/workflows/0c43ee0a-750a-4a3b-8f76-afdc2ca0f799/jobs/5371

**Comment by jfrerich** [comment]
Yes.  I am workin on that fix right now :)

**Pull request merged**
