### PR TITLE
Update jira_issue_selector.jsx

### PR DESCRIPTION
**Pull request by shwetd19**
1) Implemented Truncation for Long Issue Titles
2) Added Full Title Display on Hover:
3) Improved Error Handling and Validation Feedback:

#### Summary

This pull request addresses issue [#1077](https://github.com/mattermost/mattermost-plugin-jira/issues/1077) by implementing two key enhancements to the Jira issue selector component in the Mattermost Jira plugin. Firstly, it introduces truncation for long issue titles, ensuring that tooltips do not overflow by limiting the display to 50 characters and appending an ellipsis. Secondly, it adds full title display on hover, utilizing the `title` attribute to show the complete issue title when users hover over an item in the dropdown. These changes significantly improve the usability and readability of the plugin, especially for users interacting with long issue titles.

#### Ticket Link

  Fixes : https://github.com/mattermost/mattermost-plugin-jira/issues/1077

### CODE REVIEW

**Comment by shwetd19** [comment]
this link is not working : https://pre-release.mattermost.com/core/channels/tickets
for joining the community

**Review by mickmister — COMMENTED** [review]
Thanks for this contribution @shwetd19! I have a few questions on this:

- Can you please add a screenshot that shows the change in action?
- I think this change actually needs to be done to https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx, since that's the component with the issue
- It seems you may have prettier or similar configured that has some conflicting rules to our eslint config. Can you please run `npm run fix` in the `webapp` directory to fix the issues if they come up?

Please let me know if this makes sense. Thanks @shwetd19!

**Comment by wiggin77** [comment]
@shwetd19 are you able to address the linter issues in this PR?

**Comment by Kshitij-Katiyar** [comment]
Hey @shwetd19, are you willing to fix these CI issues?

**Comment by wiggin77** [comment]
> I think this change actually needs to be done to https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx, since that's the component with the issue

Based on Michael's comment above, amount of linter errors, and the contributor not responding, I'm thinking we should close this and have it fixed in the correct file.  Thoughts @raghavaggarwal2308 @Kshitij-Katiyar ?

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Yeah, sound good. We will recreate the PR with the changes

**Comment by Kshitij-Katiyar** [comment]
@wiggin77 The first part of #1077 was already being fixed in https://github.com/mattermost/mattermost-plugin-jira/pull/1123 and the changes of this PR were not much required in fixing the second part of #1077 
So I updated the https://github.com/mattermost/mattermost-plugin-jira/pull/1123 to completely fix #1077 
I think we can close this PR now

**Pull request closed without merging**
