### PR TITLE
Make channel subscriptions instance-specific

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR changes how the channel subscriptions are stored in the KV Store.

Instead of being stored at the key `JIRA_SUBSCRIPTIONS_KEY`, each instance's subscriptions will now be stored with their own key in the KV store. So when we access an instance's subscriptions we will use `store.keyWithInstance(ji, JIRA_SUBSCRIPTIONS_KEY)` for the key.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-16940

### CODE REVIEW

**Comment by cpoile** [comment]
@mickmister needs merge with master, then a spinmint for Dylan?

**Comment by mickmister** [comment]
Thanks @cpoile!

`/bot-server` allows one spinmint server per user, and I already have one set up for the multiple projects PR

**Comment by cpoile** [comment]
@mickmister I'm waiting on my access, probably tomorrow.

**Comment by cpoile** [comment]
@DHaussermann sever is [here](https://jira-test.test.spinmint.com). Thanks!

**Comment by mickmister** [comment]
@DHaussermann Uninstalling the instance should probably clean up its data, though I think that is out of scope of this ticket.

**Pull request merged**
