### PR TITLE
Configuration: Change “Step 3“ to “Step 4”

### PR DESCRIPTION
**Pull request by alexislefebvre**
#### Summary

The Step 3 was present twice.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
https://mattermost.org/mattermost-contributor-agreement/ asks my “Phone number or Skype ID”, I don't want to give this information. Feel free to close the PR.

**Review by hanzei — APPROVED** [review]

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Awesome, thanks for this helpful change! :)

**Comment by justinegeffen** [comment]
@alexislefebvre, I understand your hesitation to add your personal details. I'd obviously like to merge the changes you made so you have the credit for it. However, if you'd prefer to close this PR I can make the changes in a new PR. Happy with whatever works for you. :)

**Comment by alexislefebvre** [comment]
Feel free to use my changes without giving credits. :grinning:

**Pull request closed without merging**
