### PR TITLE
[MM-19179] Show user their settings with `/jira settings`

### LINKED ISSUE #315: Show user their settings with `/jira settings`
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

-----

#### Summary

Currently, `/jira settings` command requires a `name`, `value` and sets them. 
Add support for `/jira settings` (no arguments) to display all settings, in a user-friendly format. The only setting we have now is notifications anyway.

https://mattermost.atlassian.net/browse/MM-18166

### PR DESCRIPTION
**Pull request by simross**
**Summary**

This PR introduces support for filtering on field values for channel subscriptions.

**Ticket Link**

[https://mattermost.atlassian.net/browse/MM-18080](https://mattermost.atlassian.net/browse/MM-18080)

**Additional info**

Closes #315

### CODE REVIEW

**Comment by levb** [comment]
@simross, thanks for the useful contribution, and doing such comprehensive job! Please sign our CLA above.

**Comment by simross** [comment]
I can see my user name in the list of approved contributors. Should I do something else?

**Comment by simross** [comment]
@aaronrothschild screenshot of the new settings view:
[https://prnt.sc/phzgl7](https://prnt.sc/phzgl7)

**Comment by aaronrothschild** [comment]
Thanks @simross Minor nit: Could we add an indent to the second line "Notifications: on" so it sits below and indented from the header title of "Current Settings:"

**Comment by levb** [comment]
@aaronrothschild @DHaussermann ping?

**Pull request merged**
