### PR TITLE
[MM-996]: removed jwt instance from setup autocomplete

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
#### Summary
Remove the "cloud" JWT instance type from install, uninstall paths & help text.

#### What to test
Check for JWT/Cloud instance type in any command/autocomplete, i.e. install, uninstall, help etc

##### Existing
Screenshot from 2024-06-28 21-06-15
help-text-old
instance-install-old

##### Updated
Screenshot from 2024-06-28 20-58-42
help-text-new
instance-install-new

#### Issue
Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/996

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by mickmister** [comment]
@Kshitij-Katiyar Are there any remaining references to cloud or JWT?

**Comment by raghavaggarwal2308** [comment]
@Kshitij-Katiyar I think we need to remove the command from help command response as well

**Comment by Kshitij-Katiyar** [comment]
> @Kshitij-Katiyar Are there any remaining references to cloud or JWT?

@mickmister Removed jwt/cloud from helpText and instance autocomplete help text

**Review by mickmister — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by AayushChaudhary0001 — COMMENTED** [review]
The above PR has been tested for the following scenario:

- Tested the JWT/Cloud instance type in any command/autocomplete, i.e. install, uninstall, help etc

The PR was working fine for the above mentioned condition, LGTM. Approved

**Pull request merged**
