### PR TITLE
[GH-168] Bold action verb in webhook notification pretext

### PR DESCRIPTION
**Pull request by mavegaf**
#### Summary

Added bold to some verbs. 

In the case of a reopened and resolved ticket, if there are more than one changelog, the text is "updated" to I didn't make it bold.

#### Ticket Link

https://github.com/mattermost/mattermost-plugin-jira/issues/168

#### Screenshots

Screenshot from 2019-12-02 10-10-08
Screenshot from 2019-12-02 10-10-36
Screenshot from 2019-12-02 10-11-46
Screenshot from 2019-12-02 10-12-30
Screenshot from 2019-12-02 10-13-07
Screenshot from 2019-12-02 10-13-44
Screenshot from 2019-12-02 10-14-15
Screenshot from 2019-12-02 10-14-55
Screenshot from 2019-12-02 10-15-31
Screenshot from 2019-12-02 10-16-04

### CODE REVIEW

**Comment by mickmister** [comment]
@mavegaf Thanks for the great improvement! LGTM other than a question for our PM

@aaronrothschild Do you think we should have the verbs bold for updating fields?

Something like:

> Michael **updated** summary from ... to ...

or

> Michael **added** labels ...

**Comment by aaronrothschild** [comment]
@mickmister I just missed your comments that came in before mine.  I didn't notice that we excluded some state changes from being bolded.  

Sorry, @mavegaf the list below (from the original GH ticket) wasn't meant to be exhaustive.  If we could make all the verbs bolded in general that would be great. 

> for issue creation: bold created
for issue assignment: bold assigned
for issue transition: bold reopened, or resolved
for issue deletion: bold deleted
for comment creation: bold commented
for comment updates: bold edited a comment
for comment deletions: bold removed a comment

**Comment by mickmister** [comment]
Here are some cases not covered in this PR:

- (name) **mentioned** you in a new comment
- (name) **commented** on (the one for the assignee is left unbolded in the PR changes)
- (name) **updated** summary from ...
- (name) **edited** the description ...
- (name) **attached** ...

I suggest doing a find for `"` to search for any remaining verbs in the file. I apologize for the confusion @mavegaf

**Comment by mavegaf** [comment]
Sure, not problem :+1:

**Comment by mavegaf** [comment]
Added bold for edited, updated, mentioned, assigned, attached, added/removed labels,

**Comment by mickmister** [comment]
Thanks @mavegaf, it looks like there is still one instance of `commented` that is not bold:

https://github.com/mavegaf/mattermost-plugin-jira/blob/5c78a5a83ee7e41de9192aeae66abb37d81dce47/server/webhook_parser.go#L304

**Comment by mavegaf** [comment]
> Thanks @mavegaf, it looks like there is still one instance of `commented` that is not bold:
> 
> https://github.com/mavegaf/mattermost-plugin-jira/blob/5c78a5a83ee7e41de9192aeae66abb37d81dce47/server/webhook_parser.go#L304

You're right! Fixed!

**Pull request merged**
