### PR TITLE
[MM-1096]: Fixed improper markdown for Jira comments received as a subscription in mattermost

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
### Description
- Corrected Markdown formatting for Jira comments received as subscriptions in Mattermost.
- Note that Mattermost does not support colored text in Markdown; any colored text from Jira comments will be displayed as plain text in Mattermost.

**Important:** This PR employs regular expressions to identify and replace various Markdown elements. If these identifiers are present exactly as written in the comment, they will be interpreted as Markdown by Mattermost. However, the likelihood of this occurring is minimal.

### What to test
- Setup Jira plugin and create a subscription for issue comment/issue description
- Comment on an issue or update the description of a ticket
- Check the markdowns used in Jira and their equivalent markdown on Mattermost
#### Markedowns fixed in this PR
- Bold
- strikethrough
- color
- numbered list
- links
- code block
- quotes
### Ticket link
 Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/1096
 Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/599

#### Jira Comment
jira text
#### Previous Mattermost Subscription Notification
old mattermost text
Screenshot from 2024-09-02 17-12-09
#### Updated Mattermost Subscription Notification
mattermost text
Screenshot from 2024-09-02 17-12-32

### CODE REVIEW

**Review by wiggin77 — CHANGES_REQUESTED** [review]
Thanks @Kshitij-Katiyar .  This is going to require a comprehensive unit test.

**Comment by Kshitij-Katiyar** [comment]
> Thanks @Kshitij-Katiyar . This is going to require a comprehensive unit test.

@wiggin77 I have added the unit test cases for the same. Please have a look.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by raghavaggarwal2308 — APPROVED** [review]

**Comment by AayushChaudhary0001** [comment]
This PR has been tested and there is an issue found in this PR

If a user tries to add a code in the comment of any ticket in Jira through the formatting options(strictly as shown the SS below), then this text is not shown as code in Mattermost.
Please refer to the screenshots below:-

image

image

**Comment by Kshitij-Katiyar** [comment]
@AayushChaudhary0001 I have added the handling for the case you have mentioned. Please re-test and let us know if anything else is to be fixed.

**Review by AayushChaudhary0001 — APPROVED** [review]
The above issue has been resolved and all the other markdowns are working fine, LGTM. Approved.

**Pull request merged**
