### PR TITLE
Fix formatting for GitBook

### PR DESCRIPTION
**Pull request by bbodenmiller**
#### Summary
Fix formatting issue in GitBook: https://mattermost.gitbook.io/plugin-jira/setup/configuration

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @bbodenmiller! This looks great. Could you let me know what changed in the formatting - I can see the bullet types changed and would be good to keep in mind for future editing.

**Comment by bbodenmiller** [comment]
> Thanks, @bbodenmiller! This looks great. Could you let me know what changed in the formatting - I can see the bullet types changed and would be good to keep in mind for future editing.

@justinegeffen I just indented the bullets. They appear to render on GitHub without indenting but not GitBook.

**Comment by justinegeffen** [comment]
Ah! Thanks a lot, @bbodenmiller. I've noticed that does happen on some pages in prod but not GitHub. I was just doing a diff here. Really appreciate the PR for this. :)

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@jfrerich, I've merged this as it's a formatting change and not content-related.

**Pull request merged**
