### PR TITLE
Gh 691 share issue public

### PR DESCRIPTION
**Pull request by hectorgabucio**
#### Summary

Adds a "share" button to the ephemeral messages about jira issues (when viewed or created with slash commands) so that the user can press it and instantly share it with everyone on the channel.
#### Ticket Link

 Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/691

### CODE REVIEW

**Review by aaronrothschild — APPROVED** [review]
Thanks for your contribution @hectorgabucio !

**Comment by mickmister** [comment]
@hectorgabucio Is this PR still in draft mode or ready for review?

**Comment by hectorgabucio** [comment]
@mickmister I would like to add some unit tests first to cover the new code, but I guess it's ready for review.

**Review by mickmister — APPROVED** [review]
LGTM :+1: Thanks @hectorgabucio!

**Review by jfrerich — APPROVED** [review]
LGTM!  Thanks @hectorgabucio!

**Comment by jfrerich** [comment]
@DHaussermann, ping for review

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- The Share publicly button works as expected
- Ephemeral post is deleted and replaced by a public post from current user with the view
- Tested on desktop and browser
- Ensured that the share still works if the state transition was used first

No issues found. 
LGTM!

@hectorgabucio sorry for the delay on testing this. Thanks for providing this enhancement. This feature is is a huge plus and makes for a great usability improvement. Much appreciated!    

Added release testing to cover this feature.

**Pull request merged**
