### PR TITLE
Release 3.2.3

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
The changes between `v3.2.3` and `v3.2.2` can be found at https://github.com/mattermost/mattermost-plugin-jira/compare/release-3.2.2...release-3.2.3.

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-jira/issues/905

### CODE REVIEW

**Comment by DHaussermann** [comment]
@hanzei or @mickmister - The build is failing in CI here.

I also when I try to compile myself I see the following 
```
➜  mattermost-plugin-jira git:(release-3.2.3-bump) ✗ make dist
./build/bin/manifest apply
mkdir -p server/dist;
cd server && env GOOS=linux GOARCH=amd64 /opt/homebrew/bin/go build -ldflags '-X "github.com/mattermost/mattermost-plugin-jira/server/utils/telemetry.rudderWriteKey=1d5bMvdrfWClLxgK1FvV3s4U1tg" -X "main.BuildDate=Wed 25 Jan 2023 17:19:13 UTC" -X "main.BuildHash=49ac4cbf92a4d5a26ef73dd866ec7d0bf77939dc" -X "main.BuildHashShort=49ac4cb"' -trimpath -o dist/plugin-linux-amd64;
# github.com/mattermost/mattermost-plugin-jira/server
./issue.go:554:26: client.GetCreateMeta undefined (type Client has no field or method GetCreateMeta)
make: *** [server] Error 2
```

Please advise

**Comment by mickmister** [comment]
@DHaussermann I fixed a typo that was causing the error

**Comment by hanzei** [comment]
@DHaussermann https://github.com/mattermost/mattermost-plugin-jira/pull/909 is merged now. Are we good to go?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Release testing is documented here https://github.com/mattermost/mattermost-plugin-jira/issues/905#issuecomment-1409453408
- Instruction changes have been merge in

LGTM!

@hanzei please merge so we can cut a release.

**Pull request merged**
