### PR TITLE
Only show connect ephemeral when user connects

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

We were showing a connect success message when we update user defaults

### CODE REVIEW

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Feature where ephemeral post informs the user they have connected is workin
- Issue where the post was appearing on each comment and issue creation has been resolved
- Regression testing found no new issues

LGTM!

**Comment by DHaussermann** [comment]
@jfrerich and @levb since this bug is new in master and very annoying I like to see it resolved before we request a temp release to community. Please review this small change when you have a chance so we can merge this in.

**Review by jfrerich — APPROVED** [review]
Simple enough. LGTM

**Comment by DHaussermann** [comment]
@levb gentle ping that this needs review. Alternatively, is there another dev you can suggest for the 2nd review?

@aaronrothschild once this change is in master we should consider pausing any more merging of PRs so can create a 3.0.1 release.

**Review by catalintomai — APPROVED** [review]

**Pull request merged**
