### PR TITLE
[MM-20281] Show channel name at the top of subscription modal when editing a subscription

### LINKED ISSUE #424: [MM-20281] Show channel name at the top of subscription modal when editing a subscription
#### Summary

Currently, when selecting a subscription in the modal, the channel name is at the top of the modal. But when you are in edit mode, it says `Add Jira Subscription`. The channel's display name should be at the top instead.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20281

#### Screenshots

image

image

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

### PR DESCRIPTION
**Pull request by AGMETEOR**
**Summary**

MM-20281 - Show channel name at the top of subscription modal when editing a subscription 

**Ticket Link**
[https://mattermost.atlassian.net/browse/MM-20281](https://mattermost.atlassian.net/browse/MM-20281)

Fixes #424

### CODE REVIEW

**Comment by jfrerich** [comment]
Thanks @AGMETEOR!  Can you resolve the CI conflict before we merge?

**Comment by AGMETEOR** [comment]
@jfrerich master is also failing. I am thinking it's because I branched from that

**Comment by jfrerich** [comment]
@AGMETEOR yes, that is what is happening. Not need to do anything on your end.  Thanks again!

**Comment by DHaussermann** [comment]
Thanks @AGMETEOR  This is working as expected. 

I do see and error when running the full make. `make: *** [test] Error 1` @jfrerich just to confirm would this be related to the conflict mentioned above? I just want to be sure that there are no corresponding tests that need to be updated.

**Pull request merged**
