### PR TITLE
[GH-912]:Cherry picked changes from #PR 915

### PR DESCRIPTION
**Pull request by Kshitij-Katiyar**
Cherry-picked the merged commit from PR https://github.com/mattermost/mattermost-plugin-jira/pull/915 into branch release-3.2 due to the comment https://github.com/mattermost/mattermost-plugin-jira/pull/915#issuecomment-1453522988.

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
LGTM

**Comment by hanzei** [comment]
@DHaussermann Can you confirm that this PR correctly cherry-picks https://github.com/mattermost/mattermost-plugin-jira/pull/915? I.e. can you re-test it?

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Repeated tests from the previous PR agains same Jira scenarios
- Projects work as expected based on permissions
- f some projects permit target user browse but not create loading the remainader of the project list works as expected
- If some projects permit target user browse but not create - There is UI feedback.    

LGTM! 

Thanks @Kshitij-Katiyar 

cc @hanzei we should be ready to package this into a dot release.

**Review by mickmister — COMMENTED** [review]
LGTM

**Pull request merged**
