### PR TITLE
Avoid error when comment field is sent as string

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

In certain situations, a Jira webhook event that does not pertain to comments will have a comment in the payload as a string, instead of an object.

The event causing this is a issue `transition` event, which does not have a `webhookEvent` field. The expected result now occurs as an error `No webhook event`. Here's an example payload:

```
{
    "transition": {
        "workflowId": 3580030,
        "workflowName": "SW Workflow 2.3",
        "transitionId": 871,
        "transitionName": "Request CCB",
        "from_status": "In Development",
        "to_status": "In Development"
    },
    "comment": "",
    "user": {...},
    "issue": {...},
    "timestamp": 1598893874818
}

```

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/385

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
Nice catch, @mickmister 👍

**Review by levb — APPROVED** [review]

**Comment by DHaussermann** [comment]
@mickmister I'm a bit confused on this. Was this an error that was constantly reproducible? Can you provide some guidance for validating this fix?

**Comment by mickmister** [comment]
@DHaussermann I think we had discussed this error, where a customer had a transition configured on their Jira webhook. The transition event is not supported in our code, coincidentally it also caused a JSON parse error when it is sent to the plugin. There is a ticket to properly implement the transition feature https://github.com/mattermost/mattermost-plugin-jira/issues/685

One way to reproduce this is to send a modified Jira event payload with `comment` set to `""`, as it is in the example in the PR description. Instead of a JSON parse error, a different error should be printed to the logs, such as `unsupported event type`.

**Comment by mickmister** [comment]
@DHaussermann and I discussed this change, and agreed that it does not provide much value, as it doesn't actually solve the underlying issue. Reproducing the actual issue is still under investigation.

@aaronrothschild How do you feel about pushing this change out to 3.1 instead of 3.0.1 since it is low impact?

**Comment by emilyacook** [comment]
@mickmister @DHaussermann Is this waiting on anything else?

**Comment by mickmister** [comment]
This fix isn't really adding any value to the product. It is a bandaid for the fact that we don't support the transition payload, and this PR doesn't solve that. Closing until this proves useful.

**Pull request closed without merging**
