### PR TITLE
Release 3.0.1 updates

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

As noted in [the ticket](https://mattermost.atlassian.net/browse/MM-32200), `v3.0.1` should be based off of `v3.0.0` and include the following PRs:

- https://github.com/mattermost/mattermost-plugin-jira/pull/660
- https://github.com/mattermost/mattermost-plugin-jira/pull/723

This PR contains these the contents of the two PRs on top of `v3.0.0`. Version bump will come afterwards.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-32200

### CODE REVIEW

**Review by aaronrothschild — APPROVED** [review]
LGTM!

**Comment by mickmister** [comment]
Docs needed to explain that chrome should work for Jira cloud authentication again. Cookie policy changes needed to be made.

**Review by levb — COMMENTED** [review]
May I ask why not cherry-pick individual PRs, and then have a clean version bump?

**Review by levb — APPROVED** [review]

**Comment by mickmister** [comment]
@levb Done :)

**Comment by mickmister** [comment]
> May I ask why not cherry-pick individual PRs

Do you mean having a separate PR for each PR being cherry-picked?

**Comment by mickmister** [comment]
> May I ask why not cherry-pick individual PRs

@levb Do you mean having a separate PR for each PR being cherry-picked?

**Review by jfrerich — APPROVED** [review]

**Comment by DHaussermann** [comment]
I'm not sure if something is different from when https://github.com/mattermost/mattermost-plugin-jira/pull/723 was tested but I can see https://github.com/mattermost/mattermost-plugin-jira/pull/723 or a very similar issue still reproducible still reproducible with commit `d5d5ec9` deployed. At least half the time the post menu options are showing incorrectly. 

I'm working to collect more info and see if I can get 100% repo steps for dev to determine what is occuring.

**Comment by DHaussermann** [comment]
After further investigation the issue I'm seeing seems to be the same symptom as https://github.com/mattermost/mattermost-plugin-jira/issues/729
This is also occurring after issue creation. Happens for me within 3 attempts.
I have updated https://github.com/mattermost/mattermost-plugin-jira/issues/729 with details.

@aaronrothschild we should discuss the impact of this before we ship this release.

**Comment by mickmister** [comment]
@DHaussermann Since https://github.com/mattermost/mattermost-plugin-jira/issues/729 is only reproducible on a read replica instance (I think?), can we skip that issue for the purpose of this release?

**Comment by justinegeffen** [comment]
> Docs needed to explain that chrome should work for Jira cloud authentication again. Cookie policy changes needed to be made.

I've taken a look through the current docs and don't see reference to Chrome or cookie policies. However, I have created a branch for this release - would you be open to taking a look and letting me know where this (and any other) change fits in?

Thank you!

**Comment by DHaussermann** [comment]
Tested and passed
- Ensured authentication issue in Chrome is resolved (tested on Jira cloud and Jira server.
- Regression tested authentication in Desktop client 
Also regression tested core functionality
- V2 Migration  
- Installing 1 and multiple instances
- Issue and comment creation in mutole Jira projects
- Legacy webhooks on migrated instance
- New subscription webhooks
- DM notifications   
- Etc...
- https://github.com/mattermost/mattermost-plugin-jira/pull/723 will be addressed in a later release

LGTM!

**Review by DHaussermann — APPROVED** [review]
Follow-up PR is needed to actually bump the version to `3.0.1`

**Pull request merged**
