### PR TITLE
[GH-773] Jira's autolink should support issue links that contain a comment link in the URL (#773) 

### PR DESCRIPTION
**Pull request by jupriano**
* add autolink config for a comment that has a comment link at the end of the posted URL

### CODE REVIEW

**Comment by mickmister** [comment]
Hi @vicky-demansol, can you please write unit tests for this so we can see this in action? Are are some example URLs you can use:

Jira Cloud:
- https://mmtest.atlassian.net/browse/DP-454?focusedCommentId=11347

Jira Server:
- http://ec2-54-157-116-111.compute-1.amazonaws.com/browse/DKHPROJ-5?focusedCommentId=10200
- http://ec2-54-157-116-111.compute-1.amazonaws.com/browse/DKHPROJ-5?focusedCommentId=10200&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-10200

**Comment by catalintomai** [comment]
Hi @vicky-demansol - this has been stale for a while - are you actively working on it? Any ETA for it? Thanks.

**Comment by vicky-demansol** [comment]
> Hi @vicky-demansol - this has been stale for a while - are you actively working on it? Any ETA for it? Thanks.

still trying writing unit test at https://github.com/mattermost/mattermost-plugin-autolink/blob/master/server/autolink/lib_jira_test.go but get failed unit test

**Comment by vicky-demansol** [comment]
unit test example https://gist.github.com/vicky-demansol/01f54856c806fba75624e9afd84d29da write on https://github.com/mattermost/mattermost-plugin-autolink/blob/master/server/autolink/lib_jira_test.go I don't know where exactly I need to write the unit test

**Comment by mickmister** [comment]
@vicky-demansol You can add it to the test as you did your gist. For future reference, you can commit this sort of code to the PR and request feedback that way

**Comment by vicky-demansol** [comment]
> @vicky-demansol You can add it to the test as you did your gist. For future reference, you can commit this sort of code to the PR and request feedback that way

can I PR without any issue there https://github.com/mattermost/mattermost-plugin-autolink/blob/master/server/autolink

**Comment by mickmister** [comment]
Hi @vicky-demanso, please mention me so I can get a notification for this discussion 🙂. Feel free to create an issue in the Autolink repository to write the unit test.

**Comment by vicky-demansol** [comment]
Hi @mickmister i was add the unit test at https://github.com/mattermost/mattermost-plugin-autolink/pull/175

**Comment by sibasankarnayak** [comment]
LGTM !
blocking on this comment [here](https://github.com/mattermost/mattermost-plugin-jira/pull/797#issuecomment-903852080)

**Comment by hanzei** [comment]
@mickmister @jfrerich Gentle reminder to review this PR

**Comment by mickmister** [comment]
@hanzei This is blocked by https://github.com/mattermost/mattermost-plugin-autolink/pull/175#pullrequestreview-832415506

**Comment by sibasankarnayak** [comment]
Will Pick this Up

**Pull request closed without merging**
