### PR TITLE
[issue 823] Avoid sending mention DM notifications for comment updates #823

### LINKED ISSUE #823: Avoid sending mention DM notifications for comment updates
Per conversation https://community.mattermost.com/core/pl/58txyyam47fzfcxsi5sqt1igqo, we should avoid sending DM notifications for comment updates, and only send for comment creations.

### PR DESCRIPTION
**Pull request by sibasankarnayak**
avoid sending notification for update of comments

ticket here
Fixes #823

### CODE REVIEW

**Comment by mickmister** [comment]
I think the fix here is just to remove this line:

https://github.com/mattermost/mattermost-plugin-jira/blob/268b3e4f18b67fbe5f9c1d85b2054d50fba3ecd0/server/webhook_parser.go#L349

**Comment by mickmister** [comment]
The PR is currently affecting how the subscriptions feature works, which we want to avoid changing here

**Review by levb — APPROVED** [review]

**Review by jfrerich — APPROVED** [review]

**Review by dipak-demansol — APPROVED** [review]
LGTM, Tested with Dylan with below scenario.
1) when user is in the team.
2) when user is not in the Project but hes in the team.

**Comment by hanzei** [comment]
@mickmister Are you fine with merging this PR?

**Review by mickmister — APPROVED** [review]
@hanzei Sorry I've been talking to @DHaussermann offline about this. I wanted to also make sure assignees don't get `Update Comment` notifications before this is merged. I think Dylan confirmed that notifications are correctly not received in this scenario.

Considering the fix is so trivial, yes we should merge this regardless :+1:

**Pull request merged**
