### PR TITLE
[MM-39399] Bump min_server_version due to imported server dependency breaking changes

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

There is a breaking change with `5.37` server code, where the plugin will crash if:
- The plugin is importing code `5.37` or later
- The server is running `5.36` or before

This PR downgrades the dependencies of `mattermost-plugin-api` and `mattermost-server`. These two dependencies were unnecessarily upgraded when removing the workflow plugin dependency in https://github.com/mattermost/mattermost-plugin-jira/pull/781. No plugin source code is changed in this PR.

The license check is still the correct logic.

Edit: I've changed the PR so it just updates the `min_server_version`

Related PR https://github.com/mattermost/mattermost-plugin-mscalendar/pull/236

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-39399

### CODE REVIEW

**Comment by mickmister** [comment]
Closing in favor of https://github.com/mattermost/mattermost-marketplace/pull/233

**Comment by hanzei** [comment]
Same question as in https://github.com/mattermost/mattermost-plugin-mscalendar/pull/236#issuecomment-947628972

**Comment by mickmister** [comment]
Repoening, as the fix still needs to be applied here, and not just the marketplace.

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
Let's simply merge this as the fix is straight forward.

**Pull request merged**
