### PR TITLE
Add *User param to GetUserInfo to avoid read replica issue

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

There is an issue where we update user info in the kv store, and immediately try to read the info, resulting in a data inconsistency.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-jira/issues/694

### CODE REVIEW

**Review by levb — APPROVED** [review]

**Comment by levb** [comment]
2/5 I really want to see a "request-time write-through" cache implemented as part of the KV interface, so Set/Get can be used indiscriminately while handling a request. Optionally, writes can be combined/written out once if appropriate. This is a separate idea, for all plugins, cc @larkox. This is probably a 2-4 mana to implement in `experimental` and we can then migrate plugins to use it.

**Comment by DHaussermann** [comment]
Tested and passed 
- From what I can tell, this does seem to solve the issue. 
- Testing on HA server compared to the  `3.0.0` release the problem appears resolved
- We should merge this to master so we can deploy to community where more conclusive testing will take place
- I will create a follow-up issue if I can repro on community which has read replicas

**Note** I did find a separate issue in testing where the post menu options for Jira are occasionally missing. Created https://github.com/mattermost/mattermost-plugin-jira/issues/729 to address this. 

LGTM!

**Review by DHaussermann — APPROVED** [review]

**Comment by DHaussermann** [comment]
@jfrerich can you please review this so we can have it in master branch and request a temp release for community?

**Review by jfrerich — APPROVED** [review]

**Pull request merged**
