### PR TITLE
Migrate from dgrijalva/jwt-go to golang-jwt

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
- Migrate from the unmaintained library `dgrijalva/jwt-go` to `golang-jwt`
- Update `github.com/rbriski/atlassian-jwt` to a version that doesn't use  `dgrijalva/jwt-go` any longer

#### Ticket Link
https://github.com/mattermost/mattermost-plugin-jira/security/dependabot/2

### CODE REVIEW

**Review by Kshitij-Katiyar — APPROVED** [review]

**Comment by hanzei** [comment]
@AayushChaudhary0001 Can you please do some smoke testing around the JWT connection process?

**Review by AayushChaudhary0001 — COMMENTED** [review]
Tested this PR for Oauth setup and connecting the user, was working fine for these conditions. Also, subscriptions were also working fine. Although, after connecting the user from the new page where the user is redirected, he receives 2 further options to close or to disconnect from the Jira account. The user is not able to disconnect from that page.

Steps to reproduce:-
- Run the /jira connect slash command
- Connect the user through valid credentials.
- Click on the disconnect button when the user is redirected to a new page post connecting the account.

Please take a look at it.
cc: @Kshitij-Katiyar

**Comment by hanzei** [comment]
@AayushChaudhary0001 Can you confirm that the reported issue is only reproducible on this branch and not on `master`?

**Comment by AayushChaudhary0001** [comment]
@hanzei I have tested that this issue also exists on master branch and is reproducible there as well.

**Comment by hanzei** [comment]
Would you please file a separate ticket for that please, @AayushChaudhary0001?

**Comment by hanzei** [comment]
@AayushChaudhary0001 Are we good to merge this PR?

**Pull request merged**
